aliases:
    apply-coder-bjk-fleek: nix run --impure home-manager/master -- -b bak switch --flake .#ubuntu@coder-bjk-fleek
    fleeks: cd ~/workspace/fleek/examples/high
allow_broken: false
bling: high
blocklist: []
byo_git: false
ejected: true
flakedir: workspace/fleek/examples/high
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: coder-bjk-fleek
      os: linux
      username: ubuntu
track: nixos-unstable
unfree: true
users:
    - email: fleek@fleek.dev
      name: Ubuntu
      ssh_private_key_file: ""
      ssh_public_key_file: ""
      username: ubuntu
