aliases:
    apply-fleekdev: nix run --impure home-manager/master -- -b bak switch --flake .#ubuntu@fleekdev
    fleeks: cd ~/fleek/examples/none
bling: none
blocklist:
    - vscode
byo_git: false
ejected: true
flakedir: fleek/examples/none
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      hostname: fleekdev
      os: linux
      username: ubuntu
track: nixos-unstable
unfree: true
users:
    - email: bketelsen@gmail.com
      name: Brian Ketelsen
      ssh_private_key_file: ~/.ssh/id_rsa
      ssh_public_key_file: ~/.ssh/id_rsa.pub
      username: ubuntu
